spring:
  application:
    name:postgres-copy-save

  datasource:
    url: jdbc:postgresql://localhost:5432/playground?reWriteBatchedInserts=true
    username: postgres
    password: password
    driver: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 25000
    hibernate:
      ddl-auto: update
      show-sql: true